#!/bin/bash

#############################################################################
#                              Tasks Runner                                 #
#############################################################################

set -e -u -o pipefail

declare -r VERSION="0.0.1"

declare -r SCRIPT=$(basename $0)
declare -r BASE_DIR="$(dirname $(readlink ${0}))"
declare -r LIB_DIR="${BASE_DIR}/lib"
declare -r TASKS_DIR="${LIB_DIR}/tasks"

declare -r WORKING_DIR="$(pwd -P)"
declare -r NPM_DIR="${WORKING_DIR}/node_modules/.bin"
declare -r RC_FILE="${WORKING_DIR}/.trunrc"

declare -r DEFAULT_DIST_DIR="${WORKING_DIR}/dist"
declare -r DEFAULT_SRC_DIR="${WORKING_DIR}/web"

declare -ra TASKS=(
    clean
    unwatch
    watch
    watch_js
    watch_css
    watch_test
    test
    build
    build_js
    build_css
)

source "${LIB_DIR}/utils/logger.sh"
source "${LIB_DIR}/tmux.sh"

show_usage() {

    local help=

    help+="Usage: ${SCRIPT} [options] <task>\n"
    help+="Version: ${VERSION}\n"
    help+="Options:\n"
    help+=" -h: This help\n"
    help+=" -d: Debug mode\n"
    help+="Tasks available: ${TASKS[@]}\n"
    echo -e ${help} 1>&2
    exit 1
}

# Check whether all dependencies are executable
check_dependencies() {

    local deps=(
        tmux
        browserify
        exorcist
        watchify
        uglifyjs
        karma
        mocha
        phantomjs
    )

    for dep in ${deps[@]}; do
        command -v $dep > /dev/null 2>&1 || \
            error "'${dep}' is required but it is not installed."
    done
}

# Include the local node binaries if there are found
add_npm_bin_to_path() {

    [[ -d $NPM_DIR ]] && \
        export PATH="${NPM_DIR}:$PATH"
}

# Include the local configuration
include_conf() {

    [[ ! -f $RC_FILE ]] && \
        error "Configuration file '${RC_FILE}' is missing!"

    source $RC_FILE

    readonly SRC_DIR=$DEFAULT_SRC_DIR
    readonly DIST_DIR=$DEFAULT_DIST_DIR

    if [[ ! -d $DIST_DIR ]]; then
        mkdir -p "${DIST_DIR}/js"
        mkdir -p "${DIST_DIR}/css"
    fi

    info "Source: ${SRC_DIR}"
    info "Distribution: ${DIST_DIR}"
}

# Check whether the task is valid
# It returns the task name if it was found
# otherwise it returns an empty value
is_valid_task() {

    local needle="${1:-}"
    local found=

    for task in "${TASKS[@]}"; do
        if [[ $task  == $needle ]]; then
            found=$task
            break
        fi
    done

    echo ${found}
}

main() {

    local task=

    while getopts "dht:" opt; do
        case $opt in
            d) set -x;;
            h) show_usage;;
            t) task=$OPTARG;;
            *) show_usage;;
        esac
    done
    shift $((OPTIND-1))

    # Show usage if task has been specified
    [[ -z $task ]] && show_usage

    # Make sure this is valid task
    [[ -z $(is_valid_task $task) ]] && error "'${task}' is not a valid task!"

    # Let's get started
    info "${SCRIPT}@${VERSION} ${WORKING_DIR}"

    add_npm_bin_to_path
    check_dependencies
    include_conf

    if [[ $task == "build" || $task == "watch" ]]; then
        local lib_script="${LIB_DIR}/${task}.sh"
    else
        local lib_script="${TASKS_DIR}/${task}.sh"
    fi

    [[ ! -f $lib_script ]] && \
        error "'${lib_script}' script is missing in '${TASKS_DIR}'!"

    info "Starting ${task}"

    source $lib_script
}

main "$@"

exit 0
